### ISSUE TITLE
[Backend] TODO..

### ISSUE THREAD

**Issue by extends-g** [extends-g/ddhometh#2]
**Frontend**
- [x] Paginate ถ้าไม่มีหน้าต่อไป paginate ไม่ต้องขึ้น
- [x] Similar inspiration
- [x] ข้อมูลหน้าต่างๆ
- [x] Submenu
- [x] Main menu
- [x] Re-structure link

**Backend**
- [x] Change “Vision” to “Inspiration”
- [x] Project, Collection, Press validation image 5 items up.
- [x] Image size validation
- [x] Contact add field
- [x] Admin change password
- [x] Images position & get main image
- [x] User admin panel.
- [x] http header
- [x] Session
- [x] Phpcr
- [x] Cache server
- [x] Deploy step
- [x] Server setting
- [ ] Backend UI.

**ถ้าทัน**
- [ ] Images slide (Home)
- [ ] Softdelete
- [x] Rbac & User acl
- [ ] Search
